name: resocoder_repo_viewer
description: Production-grade project developed during the Reso Coder Academy
  Flutter Bootcamp.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  auto_route: ^2.2.0
  cached_network_image: ^3.1.0
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.0
  flash: ^2.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.0
  flutter_riverpod: ^1.0.0-dev.5
  flutter_secure_storage: ^4.2.0
  freezed_annotation: ^0.14.2
  json_annotation: ^4.0.1
  material_design_icons_flutter: ^5.0.5955-rc.1
  oauth2: ^2.0.0
  path: ^1.8.0
  path_provider: ^2.0.2
  sembast: ^3.1.0+2
  shimmer: ^2.0.0
  webview_flutter: ^2.0.9

dev_dependencies:
  auto_route_generator: ^2.1.0
  build_runner: ^2.0.5
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  json_serializable: ^4.1.3
  lint: ^1.5.3

flutter:
  uses-material-design: true
  assets:
    - .env
