name: resocoder_repo_viewer
description: Production-grade project developed during the Reso Coder Academy
  Flutter Bootcamp.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  auto_route: ^2.2.0
  cached_network_image: ^3.1.0
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.0
  flash: ^2.0.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.0
  flutter_riverpod: ^1.0.0-dev.7
  flutter_secure_storage: ^4.2.0
  freezed_annotation: ^0.14.2
  json_annotation: ^4.0.1
  material_design_icons_flutter: ^5.0.5955-rc.1
  material_floating_search_bar: ^0.3.4
  oauth2: ^2.0.0
  path: ^1.8.0
  path_provider: ^2.0.2
  sembast: ^3.1.0
  shimmer: ^2.0.0
  webview_flutter: ^2.0.13

dev_dependencies:
  auto_route_generator: ^2.1.0
  build_runner: ^2.0.5
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  freezed: ^0.14.2
  json_serializable: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env

flutter_icons:
  android: false
  ios: true
  image_path: "assets/icon/icon-1024x1024.png"
