name: resocoder_repo_viewer
description: Production-grade project developed during the Reso Coder Academy
  Flutter Bootcamp.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  auto_route: ^3.0.4
  cached_network_image: ^3.1.0+1
  dartz: ^0.10.0
  dio: ^4.0.1
  flash: ^2.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^1.0.0
  flutter_secure_storage: 5.0.0-beta.5
  freezed_annotation: ^0.15.0
  json_annotation: ^4.3.0
  material_design_icons_flutter: ^5.0.6295
  material_floating_search_bar: ^0.3.6
  oauth2: ^2.0.0
  path_provider: ^2.0.6
  path: ^1.8.0
  sembast: ^3.1.1
  shimmer: ^2.0.0
  webview_flutter: ^2.3.0
  url_launcher: ^6.0.12

dev_dependencies:
  auto_route_generator: ^3.0.1
  build_runner: ^2.1.4
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  freezed: ^0.15.0+1
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true
  assets:
    - .env

flutter_icons:
  android: false
  ios: true
  image_path: "assets/icon/icon-1024x1024.png"
